openapi: 3.0.3
info:
  title: Swagger Numerical Method - OpenAPI 3.0
  description: |-
    This is a sample Numerical Server based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io).
    
  termsOfService: http://swagger.io/terms/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:3000
tags:
  - name: Root Of Equation
    description: Some method about Root of Equation
  - name: Linear Algebra
    description: Some method about Linear Algebra
  - name: Least-Square Regreesion
    description: Some method about Linear Regreesion
paths:
  /Bisection:
    get:
      tags:
        - Root Of Equation
      summary: Number of problems Bisection
      description: Show Structure
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bisection'
        '400':
          description: Invalid ID supplied
        '401':
          description: Unauthorized
        '404':
          description: Problem not found
      security:
        - api_key: []
  /Bisection/{BisectionId}:
    get:
      tags:
        - Root Of Equation
      summary: Number of problems Bisection
      description: return a single problem
      operationId: getBisectionById
      parameters:
        - name: BisectionId
          in: path
          description: ID of bisection to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bisection'
        '400':
          description: Invalid ID supplied
        '401':
          description: Unauthorized
        '404':
          description: Problem not found
      security:
        - api_key: []
  /OnePoint:
    get:
      tags:
        - Root Of Equation
      summary: Number of problems OnePoint
      description: Show Structure
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OnePoint'
        '400':
          description: Invalid ID supplied
        '401':
          description: Unauthorized
        '404':
          description: Problem not found
      security:
        - api_key: []
  /Taylor:
    get:
      tags:
        - Root Of Equation
      summary: Number of problems Taylor
      description: Show Structure
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Taylor'
        '400':
          description: Invalid ID supplied
        '401':
          description: Unauthorized
        '404':
          description: Problem not found
      security:
        - api_key: []
  /Secant:
    get:
      tags:
        - Root Of Equation
      summary: Number of problems Secant
      description: Show Structure
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Secant'
        '400':
          description: Invalid ID supplied
        '401':
          description: Unauthorized
        '404':
          description: Problem not found
      security:
        - api_key: []
  /CramerRule:
    get:
      tags:
       - Linear Algebra
      summary: Number of problems CramerRule
      description: Show Structure
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CramerRule'
        '400':
          description: Invalid ID supplied
        '401':
          description: Unauthorized
        '404':
          description: Problem not found
      security:
        - api_key: []
  /PolynomialLinearRegression:
    get:
      tags:
       - Least-Square Regreesion
      summary: Number of problems Polynomial Linear Regression
      description: Show Structure
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PolynomialLinearRegression'
        '400':
          description: Invalid ID supplied
        '401':
          description: Unauthorized
        '404':
          description: Problem not found
      security:
        - api_key: []
components:
  schemas:
    Bisection:
      type: object
      properties:
        id:
          type: integer
          description: number of problem
        equation:
          type: string
          description: problem
        xl:
          type: number
          description: left scope
        xr:
          type: number
          description: right scope
    OnePoint:
      type: object
      properties:
        id:
          type: integer
          description: number of problem
        equation:
          type: string
          description: problem
        x0:
          type: number
          description: initial x
    Taylor:
      type: object
      properties:
        id:
          type: integer
          description: number of problem
        equation:
          type: string
          description: problem
        x0:
          type: number
          description: initial x start
        x:
          type: number
          description: initial x 
        n:
          type: integer
          description: number of count
    Secant:
      type: object
      properties:
        id:
          type: integer
          description: number of problem
        equation:
          type: string
          description: problem
        x0:
          type: number
          description: initial x0
        x1:
          type: number
          description: initial x1
    CramerRule:
      type: object
      properties:
        id:
          type: integer
          description: number of problem
        size:
          type: integer
          description: size of matrix
        values:
          items:
            type: array
          description: Matrix Data A, B
    PolynomialLinearRegression:
      type: object
      properties:
        id:
          type: integer
          description: number of problem
        values:
          items:
            type: array
          description: table Data X, y
        x:
          type: number
          description: input x
        n:
          type: integer
          description: table size
        order:
          type: integer
          description: number of degree
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header